name: take-tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run CI suite defined in Takefile
        uses: actions/checkout@v3
      - run: sudo apt install -y tcllib
      - run: tclsh ./src/take.tcl ci
